package jafar.mockaroo;

import lombok.Getter;

@Getter

public enum Type {
    FULLNAME,USERNAME,FIRSTNAME,LASTNAME,EMAIL,IPADDRESS,ANIMAL,BOOLEAN,BLANK,ADDRESS,ANCIENT,ARTIST,AVATAR,AVIATION,BARCODE,BASKETBALL,BEER,BOOK, BUFFY,BUSINESS,CAT,COIN,COLOR,COMMERCE,COMPANY,COUNTRY,CREDITCARD,CRYPTO,CURRENCY

}
